name: Backend Build

on:
  push:

jobs:
  ci-pipeline:
    name: Validate and Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend/rest-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Run Checkstyle
      run: ./gradlew check

    - name: Run Gradle Tests
      run: ./gradlew test
